### ISSUE TITLE
Add DTS audio support.

### ISSUE THREAD

**Issue by MinorMole** [FFMS/ffms2#316] opened 2018-03-14 16:18 UTC
Add DTS audio support. (DTS aka Digital Theater Systems)

Thank you so much.

**Comment by dwbuiten** [comment] 2018-03-14 16:21
It already supports this. What makes you think otherwise?

**Comment by MinorMole** [comment] 2018-03-14 18:33
The FFIndex return unsupported when the MKV file contains DTS audio. I tried to remux file without DTS audio and it was fine.

> FIndex: Audio format change detected. This is currently unsupported. Channels: 2 -> 2; Sample rate: 48000 -> 48000; Sample format: Unknown -> Unknown

**Comment by dwbuiten** [comment] 2018-03-16 19:57
Seems odd. It should be supported just fine. I'll find a sample and try this weekend.

**Comment by MinorMole** [comment] 2018-03-17 17:14
@dwbuiten Here is my sample

`https://drive.google.com/open?id=1Sdcc_xK-2vqoZ5eLp8uv7qjzb7KCEMJl`

**Comment by dwbuiten** [comment] 2018-03-18 15:35
Looks like our printing code was a little outdated. Updated this in 36267006185050c6d44967acadabd06a6d1c7f85 and now it shows:

`Indexing error: Audio format change detected. This is currently unsupported. Channels: 2 -> 2; Sample rate: 48000 -> 48000; Sample format: s32p -> s16p`

At least that's a little more clarity on what is happening. It's possible the DTS-HD MA extension is dropping off and just outputting the core at some point. Will look further.

**Comment by dwbuiten** [comment] 2018-03-18 15:53
Looking closer, it seems the last 2253 of 593598 total DTS frames are 16-bit (core only?), so this bug is actually a duplicate of #22, which is our oldest bug.

That's recently come up as a TODO before the next FFMS2 release.

In the meantime, you can just chop off the last 22-30 seconds of audio when you mux, which seems to e nothing but silence anyway. I'm guessing you remuxed some Blu-ray `.m2ts` directly (without the `.mpls` info), and the last 20-30 seconds are some other feature or slideshow that has silence + 16-bit core-only DTS.

Closing this for now as a duplicate of #22.

**Closed by dwbuiten** 2018-03-18 15:53 UTC
